name: EthProvider Example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.16.0
      with:
        elixir-version: '1.15.2' 
        otp-version: '26.0'      
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: examples/et_provider/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Change directory to eth_provider
      run: cd examples/eth_provider/
    - name: Install dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: Check formatting
      run: mix format --check-formatted
